### Introduction

- https://www.open3d.org/docs/release/introduction.html

#### Quick Start

```python
# Install
!pip install open3d       # or
!pip install open3d-cpu   # Smaller CPU only wheel on x86_64 Linux (v0.17+)
```

In [20]:
# Verify installation
!python -c "import open3d as o3d; print(o3d.__version__)"

0.18.0


In [1]:
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
o3d.__version__

'0.18.0'

In [ ]:
# 각 쉘에서 따로 실행하면 올바른 결과가 나오지 않음.
mesh = o3d.geometry.TriangleMesh.create_sphere()
mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([mesh])

In [1]:
import open3d as o3d
import numpy as np
import os
import sys

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

Load a ply point cloud, print it, and render it


In [4]:
sys.path.append('C:/Users/perso/open3d_data/download/PLYPointCloud/')

In [5]:
pcd = o3d.io.read_point_cloud('C:/Users/perso/open3d_data/download/PLYPointCloud/fragment.ply')
print(pcd)

PointCloud with 196133 points.


In [6]:
print(np.asarray(pcd.points))

[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


In [7]:
o3d.visualization.draw_geometries([pcd])

<img src="https://raw.githubusercontent.com/hugoMGSung/study-open3d/refs/heads/main/images/o3d_0001.png" width="500">

[실행결과]

In [8]:
pcd = o3d.io.read_point_cloud('../data/airplane.ply')
print(pcd)

PointCloud with 1335 points.


In [9]:
o3d.visualization.draw_geometries([pcd])

In [10]:
pcd = o3d.io.read_point_cloud('../data/big_porsche.ply')
print(pcd)

PointCloud with 5247 points.


In [11]:
o3d.visualization.draw_geometries([pcd])

In [ ]:
ply_point_cloud = o3d.data.ArmadilloMesh()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/ArmadilloMesh.ply
[Open3D INFO] Downloaded to C:\Users\perso/open3d_data/download/ArmadilloMesh/ArmadilloMesh.ply
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 요청한 변환 작업을 지원할 수 없습니다. 


In [14]:
o3d.visualization.draw_geometries([pcd])

In [3]:
ply_point_cloud = o3d.data.BunnyMesh()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/BunnyMesh.ply
[Open3D INFO] Downloaded to C:\Users\perso/open3d_data/download/BunnyMesh/BunnyMesh.ply


In [4]:
o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 핸들이 잘못되었습니다. 


### Point cloud
- basic usage of a point cloud

#### Visualize point cloud
- The first part of the tutorial reads a point cloud and visualize it

In [8]:
pcd = o3d.io.read_point_cloud('../data/fragment.ply')
print(pcd)

PointCloud with 196133 points.


In [9]:
o3d.visualization.draw_geometries([pcd])

#### Voxel downsampling
- Voxel downsampling uses a regular voxel grid to create a uniformly downsampled point cloud from an input point cloud.
- ...

In [10]:
downpcd = pcd.voxel_down_sample(voxel_size=0.05)

In [11]:
o3d.visualization.draw_geometries([downpcd])

#### Vertex normal estimation


In [13]:
## 여기는 잘 안됨
downpcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)
)
o3d.visualization.draw_geometries([downpcd])