In [2]:
import open3d as o3d
import numpy as np
import os
import sys

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

Load a ply point cloud, print it, and render it


In [6]:
sys.path.append('C:/Users/perso/open3d_data/download/PLYPointCloud/')

In [9]:
pcd = o3d.io.read_point_cloud('C:/Users/perso/open3d_data/download/PLYPointCloud/fragment.ply')
print(pcd)

PointCloud with 196133 points.


In [10]:
print(np.asarray(pcd.points))

[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


In [11]:
o3d.visualization.draw_geometries([pcd])