#### Tensor

In [5]:
import open3d.core as o3c
import numpy as np

In [6]:
o3c.Device

open3d.cpu.pybind.core.Device

In [7]:
from open3d._build_config import _build_config

for k,v in _build_config.items():
    print(f"{k}: {v}")

BUILD_TENSORFLOW_OPS: False
BUILD_PYTORCH_OPS: False
BUILD_CUDA_MODULE: False
BUILD_SYCL_MODULE: False
BUILD_AZURE_KINECT: True
BUILD_LIBREALSENSE: True
BUILD_SHARED_LIBS: False
BUILD_GUI: True
ENABLE_HEADLESS_RENDERING: False
BUILD_JUPYTER_EXTENSION: True
BUNDLE_OPEN3D_ML: False
GLIBCXX_USE_CXX11_ABI: True
CMAKE_BUILD_TYPE: Release
CUDA_VERSION: 
CUDA_GENCODES: 
Tensorflow_VERSION: 
Pytorch_VERSION: 
WITH_OPENMP: True


In [9]:
# Tensor from list.
a = o3c.Tensor([0, 1, 2])
print("Created from list:\n{}".format(a))

# Tensor from Numpy.
a = o3c.Tensor(np.array([0, 1, 2]))
print("\nCreated from numpy array:\n{}".format(a))

# Dtype and inferred from list.
a_float = o3c.Tensor([0.0, 1.0, 2.0])
print("\nDefault dtype and device:\n{}".format(a_float))

# Specify dtype.
a = o3c.Tensor(np.array([0, 1, 2]), dtype=o3c.Dtype.Float64)
print("\nSpecified data type:\n{}".format(a))

# Specify device.
# a = o3c.Tensor(np.array([0, 1, 2]), device=o3c.Device("CUDA:0"))
# print("\nSpecified device:\n{}".format(a))
a = o3c.Tensor(np.array([0, 1, 2]), device=o3c.Device("CPU:0"))
print("\nSpecified device:\n{}".format(a))

Created from list:
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b170370]

Created from numpy array:
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b170390]

Default dtype and device:
[0.0 1.0 2.0]
Tensor[shape={3}, stride={1}, Float64, CPU:0, 0x2853b170630]

Specified data type:
[0.0 1.0 2.0]
Tensor[shape={3}, stride={1}, Float64, CPU:0, 0x2853b170fd0]

Specified device:
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b170690]


In [10]:
# Shallow copy constructor.
vals = np.array([1, 2, 3])
src = o3c.Tensor(vals)
dst = src
src[0] += 10

# Changes in one will get reflected in other.
print("Source tensor:\n{}".format(src))
print("\nTarget tensor:\n{}".format(dst))

Source tensor:
[11 2 3]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b170cf0]

Target tensor:
[11 2 3]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b170cf0]


#### Properties of a tensor

In [12]:
vals = np.array((range(24))).reshape(2, 3, 4)
# a = o3c.Tensor(vals, dtype=o3c.Dtype.Float64, device=o3c.Device("CUDA:0"))
a = o3c.Tensor(vals, dtype=o3c.Dtype.Float64, device=o3c.Device("CPU:0"))
print(f"a.shape: {a.shape}")
print(f"a.strides: {a.strides}")
print(f"a.dtype: {a.dtype}")
print(f"a.device: {a.device}")
print(f"a.ndim: {a.ndim}")

a.shape: SizeVector[2, 3, 4]
a.strides: SizeVector[12, 4, 1]
a.dtype: Float64
a.device: CPU:0
a.ndim: 3


#### Copy & device transfer

In [20]:
# Host -> Device.
a_cpu = o3c.Tensor([0, 1, 2])
# a_gpu = a_cpu.cuda(0)
a_gpu = a_cpu
print(a_gpu)

# Device -> Host.
# a_gpu = o3c.Tensor([0, 1, 2], device=o3c.Device("CUDA:0"))
a_gpu = o3c.Tensor([0, 1, 2], device=o3c.Device("CPU:0"))
a_cpu = a_gpu.cpu()
print(a_cpu)

# Device -> another Device.
# a_gpu_0 = o3c.Tensor([0, 1, 2], device=o3c.Device("CUDA:0"))
a_gpu_0 = o3c.Tensor([0, 1, 2], device=o3c.Device("CPU:0"))
# a_gpu_1 = a_gpu_0.cuda(0)
a_gpu_1 = a_gpu_0
print(a_gpu_1)

[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b171010]
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b170c50]
[0 1 2]
Tensor[shape={3}, stride={1}, Int64, CPU:0, 0x2853b170db0]


#### PyTorch I/O with DLPack memory map
- PyTorch 설치 필요
- 현재의 예제대로면 Open3D의 CUDA와 Pytorch의 CUDA가 호환될 것이나, Open3D GPU 사용불가로 호환 안됨

In [21]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:30:10_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
